version: '3.1'

services:

  mymicor-cli:
    build: ./mymicor-cli
    environment:
      MICRO_REGISTRY: "mdns"

  mymicor-consignment:
    build: ./mymicor-consignment
    ports:
      - 50051:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "datastore:27017"

  mymicor-vessel:
    build: ./mymicor-vessel
    ports:
      - 50052:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "datastore:27017"

  user-service:
    build: ./user-service
    ports:
      - 50053:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"

  database:
    image: postgres
    ports:
      - 5432:5432

  datastore:
    image: mongo
    ports:
      - 27017:27017